version: '2'

services:

  workspace:
    build: .
    volumes:
      - ./build/transcoder:/bin/transcoder
      - ./bucket/input:/bucket/input
      - ./bucket/output:/bucket/output
#    command: /bin/bash

#  ffmpeg:
#    image: jrottenberg/ffmpeg
#    volumes:
#      - ./bucket/input:/bucket/input
#      - ./bucket/output:/bucket/output
#    command: /usr/bin/bash

#  golang:
#    image: golang:1.9
#    volumes:
#      - ./:/code
#      - ./build:/build
#    working_dir: /code
##    command: go build -o /bin/transcoder /code/cmd/transcoder/main.go
##    command: go build -o /build/transcoder /code/cmd/transcoder/main.go
#    command: /usr/local/go/bin/go

#  rabbit:
#    image: rabbitmq:3-management
#    ports:
#      - 5672:5672
#      - 15672:15672
